config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :bug_models
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug_model.rb
class BugModel < ApplicationRecord
  belongs_to :user, optional: false
  enum issue_type: [:issue, :enhancement, :feature]
  enum priority: [:low, :medium, :high]
  enum status: [:open, :closed, :monitor]

  validates :title, presence: true, length: {minimum: 5, maximum: 15}
  validates :description, presence: true, length: {minimum: 20, maximum: 600}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bug_models
  validates :lname, presence: true, length: {minimum: 1, maximum:15}
  validates :fname, presence: true, length: {minimum: 1, maximum:15}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :thumbnail, presence: false, format: { with: /\A(|.+\.(jpg|gif|png))\z/,
                                                   message: "Must end with .jpg, .gif, .png" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bug_models_controller.rb
class BugModelsController < ApplicationController
  before_action :set_bug_model, only: [:show, :edit, :update, :destroy]
  before_action :set_issue_types
  before_action :set_priorities
  before_action :set_statuses
  # GET /bug_models
  # GET /bug_models.json
  def index
    @bug_models = BugModel.all
  end

  # GET /bug_models/1
  # GET /bug_models/1.json
  def show
  end

  # GET /bug_models/new
  def new
    @bug_model = BugModel.new
  end

  # GET /bug_models/1/edit
  def edit
  end

  # POST /bug_models
  # POST /bug_models.json
  def create
    @bug_model = BugModel.new(bug_model_params)

    respond_to do |format|
      if @bug_model.save
        format.html { redirect_to @bug_model, notice: 'Bug model was successfully created.' }
        format.json { render :show, status: :created, location: @bug_model }
      else
        format.html { render :new }
        format.json { render json: @bug_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bug_models/1
  # PATCH/PUT /bug_models/1.json
  def update
    respond_to do |format|
      if @bug_model.update(bug_model_params)
        format.html { redirect_to @bug_model, notice: 'Bug model was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug_model }
      else
        format.html { render :edit }
        format.json { render json: @bug_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_models/1
  # DELETE /bug_models/1.json
  def destroy
    @bug_model.destroy
    respond_to do |format|
      format.html { redirect_to bug_models_url, notice: 'Bug model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug_model
      @bug_model = BugModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bug_model_params
      params.require(:bug_model).permit(:user_id, :title, :description, :issue_type, :priority, :status)
    end

    def set_issue_types
      @issues = BugModel.issue_types
    end

    def set_priorities
      @priorities = BugModel.priorities
    end

    def set_statuses
      @statuses = BugModel.statuses
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bug_models = BugModel.take(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :lname, :fname, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bug_models_helper.rb
module BugModelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bug_models/_form.html.erb
<%= form_with(model: bug_model, local: true) do |form| %>
    <% if bug_model.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(bug_model.errors.count, "error") %> prohibited this bug_model from being saved:</h2>

            <ul>
                <% bug_model.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :user %>
        <%= form.select :user_id, options_for_select(User.all.collect {|a| ["#{a.lname}, #{a.fname}", a.id]},
            selected: (@bug_model.user ? @bug_model.user.id : User.first.id)), {}, { class: "form-control" }%>
    </div>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control"%>
    </div>

    <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control"%>
    </div>

    <div class="field">
        <%= form.label :issue_type %>
        <%= form.select :issue_type, @issues.keys, {selected: @bug_model.issue_type}, {class: "form-control" }%>
    </div>

    <div class="field">
        <%= form.label :priority %>
        <%= form.select :priority, @priorities.keys, {selected: @bug_model.priority}, {class: "form-control" }%>
    </div>

    <div class="field">
        <%= form.label :status %>
        <%= form.select :status, @statuses.keys, {selected: @bug_model.status}, {class: "form-control" }%>
    </div>

    <div class="actions">
        <%= form.submit class: "btn btn-outline-primary"%>
    </div>
<% end %>

app/views/bug_models/edit.html.erb
<h1>Editing Bug Model</h1>

<%= render 'form', bug_model: @bug_model %>

app/views/bug_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bug Models</h1>

<table id="table" class="table">
    <thead>


        <tr>
            <th scope="col">User</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Issue type</th>
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
            <th colspan="3"></th>
        </tr>


    </thead>

    <tbody>
        <% @bug_models.each do |bug_model| %>
            <tr>
                <td><%= "#{bug_model.user.fname} #{bug_model.user.lname}" %></td>
                <td><%= bug_model.title %></td>
                <td><%= bug_model.description %></td>
                <td><%= bug_model.issue_type %></td>
                <td><%= bug_model.priority %></td>
                <td><%= bug_model.status %></td>
                <td><%= link_to 'Show', bug_model %></td>
                <td><%= link_to 'Edit', edit_bug_model_path(bug_model) %></td>
                <td><%= link_to 'Destroy', bug_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= javascript_pack_tag 'sortBugs', 'data-turbolinks-track': 'reload' %>

<%= link_to 'New Bug Model', new_bug_model_path, class: "btn btn-outline-primary" %>

app/views/bug_models/new.html.erb
<h1>New Bug Model</h1>

<%= render 'form', bug_model: @bug_model %>

app/views/bug_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug_model.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug_model.description %>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug_model.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug_model.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug_model.status %>
</p>

<%= link_to 'Edit', edit_bug_model_path(@bug_model) %> |
<%= link_to 'Back', bug_models_path %>

app/views/home/index.html.erb
<h2>Top bugs</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">User</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
        </tr>
    </thead>

    <tbody>
        <% @bug_models.each do |bug_model| %>
            <tr>
                <td><%= "#{bug_model.user.fname} #{bug_model.user.lname}" %></td>
                <td><%= bug_model.title %></td>
                <td><%= bug_model.description %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bug</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "Bugs Galore", root_path, class:"p-2 text-dark" %></h5>
            <nav class="my-2 my-md-0 mr-md-3">
                <%= link_to "Bugs", {controller: "bug_models", action: "index"}, class: "p-2 text-dark" %>
                <%= link_to "Users", {controller: "users", action: "index"}, class: "p-2 text-dark" %>
            </nav>
            <%= link_to "Sign up", {controller: "users", action: "new"}, class: "btn btn-outline-primary" %>
        </div>
        <div class="container">
            <%= yield %>
        </div>
    </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, id: 'postForm') do |form| %>
    <div id='errorMessage'>
    </div>
    <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: "email",  class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :lname %>
    <%= form.text_field :lname,id: "lname",  class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: "fname", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail, id: "thumbnail", class: "form-control"%>
  </div>

  <div class="actions">
      <%= form.submit data: {disable_with: false} %>
  </div>



  <style type="text/css">
#errorMessage {
    width  : 100%;
  padding: 0;

  font-size: 80%;
  color: white;
  background-color: #900;
  border-radius: 0 0 5px 5px;

  box-sizing: border-box;
}
</style>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= javascript_pack_tag 'postValidate', 'data-turbolinks-track': 'reload' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Lname</th>
      <th scope="col">Fname</th>
      <th scope="col">Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.lname %></td>
        <td><%= user.fname %></td>
        <td><%= user.thumbnail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-outline-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= javascript_pack_tag 'postValidate', 'data-turbolinks-track': 'reload' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @user.thumbnail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>